//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgentPonyWarcraftClassicClient.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgentPonyWarcraftClassicClient.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;code&quot;:403, &quot;type&quot;:&quot;Forbidden&quot;, &quot;detail&quot;:&quot;Account Inactive&quot;} ähnelt.
        /// </summary>
        internal static string AccountInactive403ForbiddenResponse {
            get {
                return ResourceManager.GetString("AccountInactive403ForbiddenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/2?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Alliance Auction House&quot;,
        ///      &quot;id&quot;: 2
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/6?namespace=dy [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AuctionIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("AuctionIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265/auctions/?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265/auctions/2?namespace=dynamic-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Alliance Auction House&quot;,
        ///      &quot;id&quot;: 2
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265/auctions/6?namespac [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AuctionIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("AuctionIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/7?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;id&quot;: 1065253078,
        ///      &quot;item&quot;: {
        ///        &quot;id&quot;: 3575
        ///      },
        ///      &quot;bid&quot;: 356000,
        ///      &quot;buyout&quot;: 375507,
        ///      &quot;quantity&quot;: 20,
        ///      &quot;time_left&quot;: &quot;LONG&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AuctionsResponse_ForBCC {
            get {
                return ResourceManager.GetString("AuctionsResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265/auctions/7?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265?namespace=dynamic-classic1x-eu&quot;
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;id&quot;: 21367704,
        ///      &quot;item&quot;: {
        ///        &quot;id&quot;: 2749
        ///      },
        ///      &quot;bid&quot;: 562,
        ///      &quot;buyout&quot;: 3000,
        ///      &quot;quantity&quot;: 1,
        ///      &quot;time_left&quot;: &quot;LONG&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 213 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AuctionsResponse_ForEra {
            get {
                return ResourceManager.GetString("AuctionsResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4388?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 4388,
        ///  &quot;has_queue&quot;: false,
        ///  &quot;status&quot;: {
        ///    &quot;type&quot;: &quot;UP&quot;,
        ///    &quot;name&quot;: &quot;Up&quot;
        ///  },
        ///  &quot;population&quot;: {
        ///    &quot;type&quot;: &quot;MEDIUM&quot;,
        ///    &quot;name&quot;: &quot;Medium&quot;
        ///  },
        ///  &quot;realms&quot;: [
        ///    {
        ///      &quot;id&quot;: 4388,
        ///      &quot;region&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/41?namespace=dynamic-classic-us&quot;
        ///        },
        ///        &quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ConnectedRealmResponse_ForBCC {
            get {
                return ResourceManager.GetString("ConnectedRealmResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 5265,
        ///  &quot;has_queue&quot;: false,
        ///  &quot;status&quot;: {
        ///    &quot;type&quot;: &quot;UP&quot;,
        ///    &quot;name&quot;: &quot;Up&quot;
        ///  },
        ///  &quot;population&quot;: {
        ///    &quot;type&quot;: &quot;MEDIUM&quot;,
        ///    &quot;name&quot;: &quot;Medium&quot;
        ///  },
        ///  &quot;realms&quot;: [
        ///    {
        ///      &quot;id&quot;: 5265,
        ///      &quot;region&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/region/83?namespace=dynamic-classic1x-eu&quot;
        ///        },
        ///      [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ConnectedRealmResponse_ForEra {
            get {
                return ResourceManager.GetString("ConnectedRealmResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;connected_realms&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372?namespace=dynamic-classic-us&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4373?namespace=dynamic-classic-us&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4374?namespace=dynamic-class [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ConnectedRealmsIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("ConnectedRealmsIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;connected_realms&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5214?namespace=dynamic-classic1x-eu&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5223?namespace=dynamic-classic1x-eu&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5225?namespace=dynamic [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ConnectedRealmsIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("ConnectedRealmsIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-display/30?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;zoom&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic-us/npcs/zoom/creature-display-30.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 30
        ///} ähnelt.
        /// </summary>
        internal static string CreatureDisplayMediaResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureDisplayMediaResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/creature-display/30?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;zoom&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic1x-eu/npcs/zoom/creature-display-30.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 30
        ///} ähnelt.
        /// </summary>
        internal static string CreatureDisplayMediaResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureDisplayMediaResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;creature_families&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Wolf&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/2?namespace=static-2.5.3_41812-classic-us&quot;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureFamiliesIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureFamiliesIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-family/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;creature_families&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-family/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Wolf&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-family/2?namespace=static-1.14.1_40818-class [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureFamiliesIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureFamiliesIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-family/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic-us/icons/56/ability_hunter_pet_wolf.jpg&quot;,
        ///      &quot;file_data_id&quot;: 132203
        ///    }
        ///  ],
        ///  &quot;id&quot;: 1
        ///} ähnelt.
        /// </summary>
        internal static string CreatureFamilyMediaResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureFamilyMediaResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/creature-family/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic1x-eu/icons/56/ability_hunter_pet_wolf.jpg&quot;,
        ///      &quot;file_data_id&quot;: 132203
        ///    }
        ///  ],
        ///  &quot;id&quot;: 1
        ///} ähnelt.
        /// </summary>
        internal static string CreatureFamilyMediaResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureFamilyMediaResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Wolf&quot;,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-family/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 1
        ///  }
        ///} ähnelt.
        /// </summary>
        internal static string CreatureFamilyResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureFamilyResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-family/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Wolf&quot;,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/creature-family/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    },
        ///    &quot;id&quot;: 1
        ///  }
        ///} ähnelt.
        /// </summary>
        internal static string CreatureFamilyResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureFamilyResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature/30?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 30,
        ///  &quot;name&quot;: &quot;Forest Spider&quot;,
        ///  &quot;type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Beast&quot;,
        ///    &quot;id&quot;: 1
        ///  },
        ///  &quot;family&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/3?namespace=static-2.5.3_41812-class [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature/30?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 30,
        ///  &quot;name&quot;: &quot;Forest Spider&quot;,
        ///  &quot;type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-type/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Beast&quot;,
        ///    &quot;id&quot;: 1
        ///  },
        ///  &quot;family&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-family/3?namespace=static-1.14.1_4081 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Beast&quot;
        ///} ähnelt.
        /// </summary>
        internal static string CreatureTypeResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureTypeResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-type/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Beast&quot;
        ///} ähnelt.
        /// </summary>
        internal static string CreatureTypeResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureTypeResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;creature_types&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Beast&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/2?namespace=static-2.5.3_41812-classic-us&quot;
        ///      } [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureTypesIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("CreatureTypesIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-type/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;creature_types&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-type/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Beast&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/creature-type/2?namespace=static-1.14.1_40818-classic1x-eu&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureTypesIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("CreatureTypesIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-crest/border/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;image&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic-us/guild/tabards/border_00.png&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GuildCrestBorderMediaResponse_ForBCC {
            get {
                return ResourceManager.GetString("GuildCrestBorderMediaResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/guild-crest/border/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;image&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic1x-eu/guild/tabards/border_00.png&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GuildCrestBorderMediaResponse_ForEra {
            get {
                return ResourceManager.GetString("GuildCrestBorderMediaResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/guild-crest/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;emblems&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;media&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-crest/emblem/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///        },
        ///        &quot;id&quot;: 0
        ///      }
        ///    },
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;media&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GuildCrestComponentsIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("GuildCrestComponentsIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/guild-crest/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;emblems&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;media&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/guild-crest/emblem/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///        },
        ///        &quot;id&quot;: 0
        ///      }
        ///    },
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;media&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://eu.api.blizzard.com/d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GuildCrestComponentsIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("GuildCrestComponentsIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-crest/emblem/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;image&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic-us/guild/tabards/emblem_00.png&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GuildCrestEmblemMediaResponse_ForBCC {
            get {
                return ResourceManager.GetString("GuildCrestEmblemMediaResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/guild-crest/emblem/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;image&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic1x-eu/guild/tabards/emblem_00.png&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GuildCrestEmblemMediaResponse_ForEra {
            get {
                return ResourceManager.GetString("GuildCrestEmblemMediaResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;code&quot;:404,&quot;type&quot;:&quot;BLZWEBAPI00000404&quot;,&quot;detail&quot;:&quot;Not Found&quot;} ähnelt.
        /// </summary>
        internal static string Item404ErrorResponse {
            get {
                return ResourceManager.GetString("Item404ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;item_classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClassesIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("ItemClassesIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item-class/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;item_classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item-class/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item-class/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClassesIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("ItemClassesIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;name&quot;: &quot;Consumable&quot;,
        ///  &quot;item_subclasses&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClassResponse_ForBCC {
            get {
                return ResourceManager.GetString("ItemClassResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item-class/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;name&quot;: &quot;Consumable&quot;,
        ///  &quot;item_subclasses&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    }
        ///  ]
        ///} ähnelt.
        /// </summary>
        internal static string ItemClassResponse_ForEra {
            get {
                return ResourceManager.GetString("ItemClassResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic-us/icons/56/inv_sword_39.jpg&quot;,
        ///      &quot;file_data_id&quot;: 135349
        ///    }
        ///  ],
        ///  &quot;id&quot;: 19019
        ///} ähnelt.
        /// </summary>
        internal static string ItemMediaResponse_ForBCC {
            get {
                return ResourceManager.GetString("ItemMediaResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/item/19019?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic1x-eu/icons/56/inv_sword_39.jpg&quot;,
        ///      &quot;file_data_id&quot;: 135349
        ///    }
        ///  ],
        ///  &quot;id&quot;: 19019
        ///} ähnelt.
        /// </summary>
        internal static string ItemMediaResponse_ForEra {
            get {
                return ResourceManager.GetString("ItemMediaResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item/19019?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 19019,
        ///  &quot;name&quot;: &quot;Thunderfury, Blessed Blade of the Windseeker&quot;,
        ///  &quot;quality&quot;: {
        ///    &quot;type&quot;: &quot;LEGENDARY&quot;,
        ///    &quot;name&quot;: &quot;Legendary&quot;
        ///  },
        ///  &quot;level&quot;: 80,
        ///  &quot;required_level&quot;: 60,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-2.5.3_41812-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 19019
        ///  },
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemResponse_ForBCC {
            get {
                return ResourceManager.GetString("ItemResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item/19019?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 19019,
        ///  &quot;name&quot;: &quot;Thunderfury, Blessed Blade of the Windseeker&quot;,
        ///  &quot;quality&quot;: {
        ///    &quot;type&quot;: &quot;LEGENDARY&quot;,
        ///    &quot;name&quot;: &quot;Legendary&quot;
        ///  },
        ///  &quot;level&quot;: 80,
        ///  &quot;required_level&quot;: 60,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/item/19019?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    },
        ///    &quot;id&quot;: 19019
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemResponse_ForEra {
            get {
                return ResourceManager.GetString("ItemResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;subclass_id&quot;: 0,
        ///  &quot;display_name&quot;: &quot;Consumable&quot;,
        ///  &quot;hide_subclass_in_tooltips&quot;: true
        ///} ähnelt.
        /// </summary>
        internal static string ItemSubclassResponse_ForBCC {
            get {
                return ResourceManager.GetString("ItemSubclassResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;subclass_id&quot;: 0,
        ///  &quot;display_name&quot;: &quot;Consumable&quot;,
        ///  &quot;hide_subclass_in_tooltips&quot;: true
        ///} ähnelt.
        /// </summary>
        internal static string ItemSubclassResponse_ForEra {
            get {
                return ResourceManager.GetString("ItemSubclassResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Warrior&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/2?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableClassesIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PlayableClassesIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-class/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-class/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Warrior&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-class/2?namespace=static-1.14.1_40818-classic1x-eu&quot;
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableClassesIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PlayableClassesIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/playable-class/7?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic-us/icons/56/classicon_shaman.jpg&quot;,
        ///      &quot;file_data_id&quot;: 626006
        ///    }
        ///  ],
        ///  &quot;id&quot;: 7
        ///} ähnelt.
        /// </summary>
        internal static string PlayableClassMediaResponse_ForBCC {
            get {
                return ResourceManager.GetString("PlayableClassMediaResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/media/playable-class/7?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render.worldofwarcraft.com/classic1x-eu/icons/56/classicon_shaman.jpg&quot;,
        ///      &quot;file_data_id&quot;: 626006
        ///    }
        ///  ],
        ///  &quot;id&quot;: 7
        ///} ähnelt.
        /// </summary>
        internal static string PlayableClassMediaResponse_ForEra {
            get {
                return ResourceManager.GetString("PlayableClassMediaResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/7?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 7,
        ///  &quot;name&quot;: &quot;Shaman&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Shaman&quot;,
        ///    &quot;female&quot;: &quot;Shaman&quot;
        ///  },
        ///  &quot;power_type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Mana&quot;,
        ///    &quot;id&quot;: 0
        ///  },
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.bli [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableClassResponse_ForBCC {
            get {
                return ResourceManager.GetString("PlayableClassResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-class/7?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 7,
        ///  &quot;name&quot;: &quot;Shaman&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Shaman&quot;,
        ///    &quot;female&quot;: &quot;Shaman&quot;
        ///  },
        ///  &quot;power_type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/power-type/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Mana&quot;,
        ///    &quot;id&quot;: 0
        ///  },
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableClassResponse_ForEra {
            get {
                return ResourceManager.GetString("PlayableClassResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 2,
        ///  &quot;name&quot;: &quot;Orc&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Orc&quot;,
        ///    &quot;female&quot;: &quot;Orc&quot;
        ///  },
        ///  &quot;faction&quot;: {
        ///    &quot;type&quot;: &quot;HORDE&quot;,
        ///    &quot;name&quot;: &quot;Horde&quot;
        ///  },
        ///  &quot;is_selectable&quot;: true,
        ///  &quot;is_allied_race&quot;: false
        ///} ähnelt.
        /// </summary>
        internal static string PlayableRaceResponse_ForBCC {
            get {
                return ResourceManager.GetString("PlayableRaceResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-race/2?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 2,
        ///  &quot;name&quot;: &quot;Orc&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Orc&quot;,
        ///    &quot;female&quot;: &quot;Orc&quot;
        ///  },
        ///  &quot;faction&quot;: {
        ///    &quot;type&quot;: &quot;HORDE&quot;,
        ///    &quot;name&quot;: &quot;Horde&quot;
        ///  },
        ///  &quot;is_selectable&quot;: true,
        ///  &quot;is_allied_race&quot;: false
        ///} ähnelt.
        /// </summary>
        internal static string PlayableRaceResponse_ForEra {
            get {
                return ResourceManager.GetString("PlayableRaceResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;races&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Human&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///       [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableRacesIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PlayableRacesIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-race/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;races&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-race/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Human&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/playable-race/2?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      } [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableRacesIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PlayableRacesIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 0,
        ///  &quot;name&quot;: &quot;Mana&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PowerTypeResponse_ForBCC {
            get {
                return ResourceManager.GetString("PowerTypeResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/power-type/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 0,
        ///  &quot;name&quot;: &quot;Mana&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PowerTypeResponse_ForEra {
            get {
                return ResourceManager.GetString("PowerTypeResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/?namespace=static-2.5.3_41812-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;power_types&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Mana&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/1?namespace=static-2.5.3_41812-classic-us&quot;
        ///      },
        ///      &quot;nam [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PowerTypesIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PowerTypesIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/power-type/?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;power_types&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/power-type/0?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Mana&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/power-type/1?namespace=static-1.14.1_40818-classic1x-eu&quot;
        ///      },
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PowerTypesIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PowerTypesIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2/pvp-leaderboard/3v3?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;season&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 2
        ///  },
        ///  &quot;name&quot;: &quot;3v3&quot;,
        ///  &quot;bracket&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;type&quot;: &quot;ARENA_3v3&quot;
        ///  },
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;faction&quot;: {
        ///        &quot;type&quot;: &quot;ALLIANCE&quot;
        ///      },
        ///      &quot;rank&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpLeaderboardResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpLeaderboardResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpLeaderboardResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpLeaderboardResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2/pvp-leaderboard/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;season&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 2
        ///  },
        ///  &quot;leaderboards&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2/pvp-leaderboard/2v2?namespace=dynamic-classic-us&quot;
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpLeaderboardsIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpLeaderboardsIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpLeaderboardsIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpLeaderboardsIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;seasons&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/1?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;id&quot;: 2
        ///    },
        ///    {
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpRegionalSeasonIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpRegionalSeasonIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpRegionalSeasonIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpRegionalSeasonIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 2,
        ///  &quot;leaderboards&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2/pvp-leaderboard/?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;rewards&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2/pvp-reward/?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;season_start_timestamp&quot;: 1631631600000,
        ///  &quot;season [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpRegionalSeasonResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpRegionalSeasonResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpRegionalSeasonResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpRegionalSeasonResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;pvp_regions&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/?namespace=dynamic-classic-us&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/2/pvp-season/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  ]
        ///} ähnelt.
        /// </summary>
        internal static string PvpRegionIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpRegionIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpRegionIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpRegionIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2/pvp-reward/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;season&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 2
        ///  },
        ///  &quot;rewards&quot;: [
        ///    {
        ///      &quot;bracket&quot;: {
        ///        &quot;id&quot;: 0,
        ///        &quot;type&quot;: &quot;ARENA_2v2&quot;
        ///      },
        ///      &quot;achievement&quot;: {
        ///        &quot;name&quot;: &quot;Merciless Gladiator&quot;,
        ///        &quot;id&quot;: 41 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpRewardsIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpRewardsIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpRewardsIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpRewardsIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 2,
        ///  &quot;season_start_timestamp&quot;: 1631631600000,
        ///  &quot;season_end_timestamp&quot;: 1641880800000,
        ///  &quot;pvp_regions&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/1/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-region/2/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///    }
        ///  ]
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpSeasonResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpSeasonResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpSeasonResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpSeasonResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;seasons&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/1?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/2?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;id&quot;: 2
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https:/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpSeasonsIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("PvpSeasonsIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PvpSeasonsIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("PvpSeasonsIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;realms&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/4372?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Atiesh&quot;,
        ///      &quot;id&quot;: 4372,
        ///      &quot;slug&quot;: &quot;atiesh&quot;
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/4373?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Myzrael&quot;,
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RealmIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("RealmIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/realm/?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;realms&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/realm/5198?namespace=dynamic-classic1x-eu&quot;
        ///      },
        ///      &quot;name&quot;: &quot;EU4 CWOW GMSS 2&quot;,
        ///      &quot;id&quot;: 5198,
        ///      &quot;slug&quot;: &quot;eu4-cwow-gmss-2&quot;
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/realm/5199?namespace=dynamic-classic1x-eu&quot;
        ///      },
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RealmIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("RealmIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/westfall?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 4388,
        ///  &quot;region&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/41?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Classic North America&quot;,
        ///    &quot;id&quot;: 41
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4388?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;name&quot;: &quot;Westfall&quot;,
        ///  &quot;categor [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RealmResponse_ForBCC {
            get {
                return ResourceManager.GetString("RealmResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/realm/ironfoe?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 5265,
        ///  &quot;region&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/region/83?namespace=dynamic-classic1x-eu&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Classic Era Europe&quot;,
        ///    &quot;id&quot;: 83
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/connected-realm/5265?namespace=dynamic-classic1x-eu&quot;
        ///  },
        ///  &quot;name&quot;: &quot;Ironfoe&quot;,
        ///  &quot;catego [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RealmResponse_ForEra {
            get {
                return ResourceManager.GetString("RealmResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/41?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 41,
        ///  &quot;name&quot;: &quot;Classic North America&quot;,
        ///  &quot;tag&quot;: &quot;US&quot;
        ///} ähnelt.
        /// </summary>
        internal static string RegionResponse_ForBCC {
            get {
                return ResourceManager.GetString("RegionResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/region/83?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 83,
        ///  &quot;name&quot;: &quot;Classic Era Europe&quot;,
        ///  &quot;tag&quot;: &quot;EU&quot;
        ///} ähnelt.
        /// </summary>
        internal static string RegionResponse_ForEra {
            get {
                return ResourceManager.GetString("RegionResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;regions&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/41?namespace=dynamic-classic-us&quot;
        ///    }
        ///  ]
        ///} ähnelt.
        /// </summary>
        internal static string RegionsIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("RegionsIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/region/?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  },
        ///  &quot;regions&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://eu.api.blizzard.com/data/wow/region/83?namespace=dynamic-classic1x-eu&quot;
        ///    }
        ///  ]
        ///} ähnelt.
        /// </summary>
        internal static string RegionsIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("RegionsIndexResponse_ForEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://gateway.battlenet.com.cn/data/wow/token/?namespace=dynamic-classic-cn&quot;
        ///    }
        ///  },
        ///  &quot;last_updated_timestamp&quot;: 1644164675000,
        ///  &quot;price&quot;: 19530000
        ///} ähnelt.
        /// </summary>
        internal static string WowTokenIndexResponse_ForBCC {
            get {
                return ResourceManager.GetString("WowTokenIndexResponse_ForBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;code&quot;: 404,
        ///  &quot;type&quot;: &quot;BLZWEBAPI00000404&quot;,
        ///  &quot;detail&quot;: &quot;Not Found&quot;
        ///} ähnelt.
        /// </summary>
        internal static string WowTokenIndexResponse_ForEra {
            get {
                return ResourceManager.GetString("WowTokenIndexResponse_ForEra", resourceCulture);
            }
        }
    }
}
