//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgentPonyWarcraftClassicClient.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgentPonyWarcraftClassicClient.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;code&quot;:403, &quot;type&quot;:&quot;Forbidden&quot;, &quot;detail&quot;:&quot;Account Inactive&quot;} ähnelt.
        /// </summary>
        internal static string AccountInactive403ForbiddenResponse {
            get {
                return ResourceManager.GetString("AccountInactive403ForbiddenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/2?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Alliance Auction House&quot;,
        ///      &quot;id&quot;: 2
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/6?namespace=dy [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AuctionIndexResponse {
            get {
                return ResourceManager.GetString("AuctionIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/5139/auctions/6?namespace=dynamic-classic1x-us&quot;
        ///    }
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/5139?namespace=dynamic-classic1x-us&quot;
        ///  },
        ///  &quot;auctions&quot;: [
        ///    {
        ///      &quot;id&quot;: 24149940,
        ///      &quot;item&quot;: {
        ///        &quot;id&quot;: 2865
        ///      },
        ///      &quot;bid&quot;: 2500,
        ///      &quot;buyout&quot;: 2500,
        ///      &quot;quantity&quot;: 1,
        ///      &quot;time_left&quot;: &quot;LONG&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 24 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AuctionsResponse {
            get {
                return ResourceManager.GetString("AuctionsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/11?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 11,
        ///  &quot;has_queue&quot;: false,
        ///  &quot;status&quot;: {
        ///    &quot;type&quot;: &quot;UP&quot;,
        ///    &quot;name&quot;: &quot;Up&quot;
        ///  },
        ///  &quot;population&quot;: {
        ///    &quot;type&quot;: &quot;FULL&quot;,
        ///    &quot;name&quot;: &quot;Full&quot;
        ///  },
        ///  &quot;realms&quot;: [
        ///    {
        ///      &quot;id&quot;: 11,
        ///      &quot;region&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/1?namespace=dynamic-classic-us&quot;
        ///        },
        ///        &quot;name&quot;: &quot;Nor [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ConnectedRealmResponse {
            get {
                return ResourceManager.GetString("ConnectedRealmResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;connected_realms&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/4?namespace=dynamic-classic-us&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/5?namespace=dynamic-classic-us&quot;
        ///    },
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/7?namespace=dynamic-classic-us&quot;
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ConnectedRealmsIndexResponse {
            get {
                return ResourceManager.GetString("ConnectedRealmsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-display/30221?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;zoom&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/npcs/zoom/creature-display-30221.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 30221
        ///} ähnelt.
        /// </summary>
        internal static string CreatureDisplayMediaResponse {
            get {
                return ResourceManager.GetString("CreatureDisplayMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;creature_families&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Wolf&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureFamiliesIndexResponse {
            get {
                return ResourceManager.GetString("CreatureFamiliesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-family/1?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/ability_hunter_pet_wolf.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 1
        ///} ähnelt.
        /// </summary>
        internal static string CreatureFamilyMediaResponse {
            get {
                return ResourceManager.GetString("CreatureFamilyMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/1?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Wolf&quot;,
        ///  &quot;specialization&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-specialization/74?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Ferocity&quot;,
        ///    &quot;id&quot;: 74
        ///  },
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/creature-family/1?namespace=static-8.3.0_3 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureFamilyResponse {
            get {
                return ResourceManager.GetString("CreatureFamilyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature/42722?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 42722,
        ///  &quot;name&quot;: &quot;Young Mastiff&quot;,
        ///  &quot;type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/1?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Beast&quot;,
        ///    &quot;id&quot;: 1
        ///  },
        ///  &quot;family&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-family/52?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureResponse {
            get {
                return ResourceManager.GetString("CreatureResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/1?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Beast&quot;
        ///} ähnelt.
        /// </summary>
        internal static string CreatureTypeResponse {
            get {
                return ResourceManager.GetString("CreatureTypeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;creature_types&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Beast&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/creature-type/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Dragon [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreatureTypesIndexResponse {
            get {
                return ResourceManager.GetString("CreatureTypesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-crest/border/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;image&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/guild/tabards/border_00.png&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GuildCrestBorderMediaResponse {
            get {
                return ResourceManager.GetString("GuildCrestBorderMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/guild-crest/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;emblems&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;media&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-crest/emblem/0?namespace=static-8.3.0_32861-us&quot;
        ///        },
        ///        &quot;id&quot;: 0
        ///      }
        ///    },
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;media&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-cr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GuildCrestComponentsIndexResponse {
            get {
                return ResourceManager.GetString("GuildCrestComponentsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/guild-crest/emblem/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;image&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/guild/tabards/emblem_00.png&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string GuildCrestEmblemMediaResponse {
            get {
                return ResourceManager.GetString("GuildCrestEmblemMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;code&quot;:404,&quot;type&quot;:&quot;BLZWEBAPI00000404&quot;,&quot;detail&quot;:&quot;Not Found&quot;} ähnelt.
        /// </summary>
        internal static string Item404ErrorResponse {
            get {
                return ResourceManager.GetString("Item404ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;item_classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Consumable&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Container&quot;,        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClassesIndexResponse {
            get {
                return ResourceManager.GetString("ItemClassesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;name&quot;: &quot;Consumable&quot;,
        ///  &quot;item_subclasses&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Explosives and Devices&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-clas [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClassResponse {
            get {
                return ResourceManager.GetString("ItemClassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/inv_sword_39.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 19019
        ///} ähnelt.
        /// </summary>
        internal static string ItemMediaResponse {
            get {
                return ResourceManager.GetString("ItemMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 19019,
        ///  &quot;name&quot;: &quot;Thunderfury, Blessed Blade of the Windseeker&quot;,
        ///  &quot;quality&quot;: {
        ///    &quot;type&quot;: &quot;LEGENDARY&quot;,
        ///    &quot;name&quot;: &quot;Legendary&quot;
        ///  },
        ///  &quot;level&quot;: 58,
        ///  &quot;required_level&quot;: 60,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/item/19019?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;id&quot;: 19019
        ///  },
        ///  &quot;item_class&quot;: {        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemResponse {
            get {
                return ResourceManager.GetString("ItemResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/item-class/0/item-subclass/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;class_id&quot;: 0,
        ///  &quot;subclass_id&quot;: 0,
        ///  &quot;display_name&quot;: &quot;Explosives and Devices&quot;,
        ///  &quot;hide_subclass_in_tooltips&quot;: true
        ///} ähnelt.
        /// </summary>
        internal static string ItemSubclassResponse {
            get {
                return ResourceManager.GetString("ItemSubclassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;classes&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Warrior&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Paladin&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableClassesIndexResponse {
            get {
                return ResourceManager.GetString("PlayableClassesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/playable-class/7?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/classicon_shaman.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 7
        ///} ähnelt.
        /// </summary>
        internal static string PlayableClassMediaResponse {
            get {
                return ResourceManager.GetString("PlayableClassMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-class/7?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 7,
        ///  &quot;name&quot;: &quot;Shaman&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Shaman&quot;,
        ///    &quot;female&quot;: &quot;Shaman&quot;
        ///  },
        ///  &quot;power_type&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Mana&quot;,
        ///    &quot;id&quot;: 0
        ///  },
        ///  &quot;specializations&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.ap [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableClassResponse {
            get {
                return ResourceManager.GetString("PlayableClassResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 2,
        ///  &quot;name&quot;: &quot;Orc&quot;,
        ///  &quot;gender_name&quot;: {
        ///    &quot;male&quot;: &quot;Orc&quot;,
        ///    &quot;female&quot;: &quot;Orc&quot;
        ///  },
        ///  &quot;faction&quot;: {
        ///    &quot;type&quot;: &quot;HORDE&quot;,
        ///    &quot;name&quot;: &quot;Horde&quot;
        ///  },
        ///  &quot;is_selectable&quot;: true,
        ///  &quot;is_allied_race&quot;: false
        ///} ähnelt.
        /// </summary>
        internal static string PlayableRaceResponse {
            get {
                return ResourceManager.GetString("PlayableRaceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;races&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Human&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-race/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Orc&quot;,
        ///      &quot;i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PlayableRacesIndexResponse {
            get {
                return ResourceManager.GetString("PlayableRacesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 0,
        ///  &quot;name&quot;: &quot;Mana&quot;
        ///} ähnelt.
        /// </summary>
        internal static string PowerTypeResponse {
            get {
                return ResourceManager.GetString("PowerTypeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;power_types&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/0?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Mana&quot;,
        ///      &quot;id&quot;: 0
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/power-type/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Rage&quot;,
        ///      &quot;id&quot;: [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PowerTypesIndexResponse {
            get {
                return ResourceManager.GetString("PowerTypesIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27/pvp-leaderboard/3v3?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;season&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 27
        ///  },
        ///  &quot;name&quot;: &quot;3v3&quot;,
        ///  &quot;bracket&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;type&quot;: &quot;ARENA_3v3&quot;
        ///  },
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;character&quot;: {
        ///        &quot;name&quot;: &quot;Chunlî&quot;,
        ///        &quot;id&quot;: 191561142,
        ///        &quot;realm&quot;: { [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpLeaderboardResponse {
            get {
                return ResourceManager.GetString("PvpLeaderboardResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27/pvp-leaderboard/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;season&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 27
        ///  },
        ///  &quot;leaderboards&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27/pvp-leaderboard/2v2?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;2v2&quot;,
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpLeaderboardsIndexResponse {
            get {
                return ResourceManager.GetString("PvpLeaderboardsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27/pvp-reward/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;season&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;id&quot;: 27
        ///  },
        ///  &quot;rewards&quot;: [
        ///    {
        ///      &quot;bracket&quot;: {
        ///        &quot;id&quot;: 3,
        ///        &quot;type&quot;: &quot;BATTLEGROUNDS&quot;
        ///      },
        ///      &quot;achievement&quot;: {
        ///        &quot;key&quot;: {
        ///          &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpRewardsIndexResponse {
            get {
                return ResourceManager.GetString("PvpRewardsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 27,
        ///  &quot;leaderboards&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27/pvp-leaderboard/?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;rewards&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/27/pvp-reward/?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;season_start_timestamp&quot;: 1548169200000,
        ///  &quot;season_end_timestamp&quot;: 1561471200000
        ///} ähnelt.
        /// </summary>
        internal static string PvpSeasonResponse {
            get {
                return ResourceManager.GetString("PvpSeasonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;seasons&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/22?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;id&quot;: 22
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-season/23?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;id&quot;: 23
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;htt [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpSeasonsIndexResponse {
            get {
                return ResourceManager.GetString("PvpSeasonsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-talent/11?namespace=static-9.0.2_36532-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 11,
        ///  &quot;spell&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/spell/199954?namespace=static-9.0.2_36532-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;Bane of Fragility&quot;,
        ///    &quot;id&quot;: 199954
        ///  },
        ///  &quot;playable_specialization&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/playable-specialization/265?namespace=static-9.0.2_36532-us&quot;
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpTalentResponse {
            get {
                return ResourceManager.GetString("PvpTalentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-talent/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;pvp_talents&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-talent/3?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Gladiator&apos;s Medallion&quot;,
        ///      &quot;id&quot;: 3
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-talent/4?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Ad [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpTalentsIndexResponse {
            get {
                return ResourceManager.GetString("PvpTalentsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/pvp-tier/1?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;assets&quot;: [
        ///    {
        ///      &quot;key&quot;: &quot;icon&quot;,
        ///      &quot;value&quot;: &quot;https://render-us.worldofwarcraft.com/icons/56/ui_rankedpvp_01.jpg&quot;
        ///    }
        ///  ],
        ///  &quot;id&quot;: 1
        ///} ähnelt.
        /// </summary>
        internal static string PvpTierMediaResponse {
            get {
                return ResourceManager.GetString("PvpTierMediaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-tier/1?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;Unranked&quot;,
        ///  &quot;min_rating&quot;: 0,
        ///  &quot;max_rating&quot;: 1400,
        ///  &quot;media&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/media/pvp-tier/1?namespace=static-8.3.0_32861-us&quot;
        ///    },
        ///    &quot;id&quot;: 1
        ///  },
        ///  &quot;bracket&quot;: {
        ///    &quot;id&quot;: 0,
        ///    &quot;type&quot;: &quot;ARENA_2v2&quot;
        ///  },
        ///  &quot;rating_type&quot;: 0
        ///} ähnelt.
        /// </summary>
        internal static string PvpTierResponse {
            get {
                return ResourceManager.GetString("PvpTierResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-tier/?namespace=static-8.3.0_32861-us&quot;
        ///    }
        ///  },
        ///  &quot;tiers&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-tier/1?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Unranked&quot;,
        ///      &quot;id&quot;: 1
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/pvp-tier/2?namespace=static-8.3.0_32861-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Combatant&quot;,
        ///      &quot;id&quot;: 2        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PvpTiersIndexResponse {
            get {
                return ResourceManager.GetString("PvpTiersIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;realms&quot;: [
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/1?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Lightbringer&quot;,
        ///      &quot;id&quot;: 1,
        ///      &quot;slug&quot;: &quot;lightbringer&quot;
        ///    },
        ///    {
        ///      &quot;key&quot;: {
        ///        &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/2?namespace=dynamic-classic-us&quot;
        ///      },
        ///      &quot;name&quot;: &quot;Cenarius&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RealmIndexResponse {
            get {
                return ResourceManager.GetString("RealmIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/realm/tichondrius?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 11,
        ///  &quot;region&quot;: {
        ///    &quot;key&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/1?namespace=dynamic-classic-us&quot;
        ///    },
        ///    &quot;name&quot;: &quot;North America&quot;,
        ///    &quot;id&quot;: 1
        ///  },
        ///  &quot;connected_realm&quot;: {
        ///    &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/connected-realm/11?namespace=dynamic-classic-us&quot;
        ///  },
        ///  &quot;name&quot;: &quot;Tichondrius&quot;,
        ///  &quot;category&quot;: &quot;Uni [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RealmResponse {
            get {
                return ResourceManager.GetString("RealmResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/1?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;id&quot;: 1,
        ///  &quot;name&quot;: &quot;North America&quot;,
        ///  &quot;tag&quot;: &quot;US&quot;
        ///} ähnelt.
        /// </summary>
        internal static string RegionResponse {
            get {
                return ResourceManager.GetString("RegionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;regions&quot;: [
        ///    {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/region/1?namespace=dynamic-classic-us&quot;
        ///    }
        ///  ]
        ///} ähnelt.
        /// </summary>
        internal static string RegionsIndexResponse {
            get {
                return ResourceManager.GetString("RegionsIndexResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;_links&quot;: {
        ///    &quot;self&quot;: {
        ///      &quot;href&quot;: &quot;https://us.api.blizzard.com/data/wow/token/?namespace=dynamic-classic-us&quot;
        ///    }
        ///  },
        ///  &quot;last_updated_timestamp&quot;: 1594853730000,
        ///  &quot;price&quot;: 1203380000
        ///} ähnelt.
        /// </summary>
        internal static string WowTokenIndexResponse {
            get {
                return ResourceManager.GetString("WowTokenIndexResponse", resourceCulture);
            }
        }
    }
}
